##########################################################################
###				             CISCO ROUTER PROMPTS FILE
###							 Version v20150121.01
##########################################################################

#Conditions names can contain only alphabet and numeric characters
[conditions]
#Standard prompts
StandardPrompt=.*\> ?$
StandardEnablePrompt=.*\# ?$
StandardConfigPrompt=.*\(config\).*\# ?$
StandardLineConfigPrompt=.*\(config-line\).*\# ?$

#Switch to enable mode
IsEnablePassObjNotExists=(expression)([string equal -nocase "<pmextrapass1>" ""] || <pmmaxextrapassindex> == 0) && (![string equal -nocase "<Type>" "ciscoenable"])
IsEnablePassObjExists=(expression)(![string equal -nocase "<pmextrapass1>" ""] && <pmmaxextrapassindex> \>= 1) 

#Check login user
IsLoginObjExists=(expression)![string equal -nocase "<pmextrapass2>" ""]
IsLoginObjNotExists=(expression)[string equal -nocase "<pmextrapass2>" ""]
IsEnableAndLoginObjExists=(expression)(![string equal -nocase "<pmextrapass2>" ""]) && ([string equal -nocase "<Type>" "ciscoenable"])
IsNoEnableAndLoginObjExists=(expression)(![string equal -nocase "<pmextrapass2>" ""]) && (![string equal -nocase "<Type>" "ciscoenable"])

#Login sequence
Login=Username:|login as:
Password=Password: 
InvalidLogin=Login invalid|Authentication failed|Access denied
BadNewPassword=Password too short|.*\(cleartext\) user password|.*Set exec level password
PlinkStoreKey=Store key in cache

#Check user type
CiscoUser=(expression)[string equal -nocase "<Type>" "ciscouser"]
CiscoTerminal=(expression)[string equal -nocase "<Type>" "ciscoterminal"]
CiscoEnable=(expression)[string equal -nocase "<Type>" "ciscoenable"]

#Copy to NVRAM
DestFile=Destination filename \[startup-config\]\?
CommitOK=\[OK\]
IsCommitSpecified=(expression)[string equal -nocase "<commit>" "yes"]
IsCommitNotSpecified=(expression)![string equal -nocase "<commit>" "yes"]

#Check protocol
ProtocolIsSSH=(expression)[string equal -nocase "<Protocol>" "ssh"]
ProtocolIsTelnet=(expression)[string equal -nocase "<Protocol>" "telnet"]

#Check which action chosen
ActionIsLogon=(expression)[string equal -nocase "<action>" "logon"]
ActionIsNotLogon=(expression)[string equal -nocase "<action>" "changepass"]
ActionIsVerify=(expression)[string equal -nocase "<action>" "verifypass"]
ActionIsReconcile=(expression)[string equal -nocase "<action>" "reconcilepass"]
ActionIsLogonOrChange=(expression)[string equal -nocase "<action>" "logon"]||[string equal -nocase "<action>" "changepass"]
ActionIsPreReconcile=(expression)[string equal -nocase "<action>" "prereconcilepass"]
ActionIsReconcileOrPreReconcile=(expression)[string equal -nocase "<action>" "reconcilepass"]||[string equal -nocase "<action>" "prereconcilepass"]

IsVerifyLogon=(expression)$verifyLogon == 1

TRUE=(expression)true

UnableToConnect=FATAL ERROR:|Unable to open connection:


#GetUserPrompt - Conditions/Prompt
#GeneralLoginSuccess = StandartPrompt or EnablePrompt
GeneralLoginSuccess=.*\> ?$ | .*\# ?$
VerifyUser=(expression)[string equal -nocase "<action>" "verifypass"]&&[string equal -nocase "<Type>" "ciscouser"]
VerifyTerminal=(expression)[string equal -nocase "<action>" "verifypass"]&&[string equal -nocase "<Type>" "ciscoterminal"]
VerifyEnable=(expression)[string equal -nocase "<action>" "verifypass"]&&[string equal -nocase "<Type>" "ciscoenable"]
IsTarget=(expression)$bTarget == 1
IsNotTarget=(expression)$bTarget == 0
IsEnablePromptFlagOn=(expression)$bEnablePrompt == 1
IsStandardPromptFlagOn=(expression)$bEnablePrompt == 0

#GetPrivMode - Conditions/Prompt
IsRecForEnable=(expression)[string equal -nocase "<Type>" "ciscoenable"]
IsNotRecForEnable=(expression)![string equal -nocase "<Type>" "ciscoenable"]

RecExt3Exist=(expression)![string equal -nocase "<pmextrapass3>" ""]
RecExt3EnableAccountExist=(expression)![string equal -nocase "<pmextrapass3\pmextrapass1>" ""]
RecExt2EnableAccountExist=(expression)![string equal -nocase "<pmextrapass2\pmextrapass1>" ""]
VerifyAfterRec=(expression)$bVerifyRecPass == 1
VerifyEnableAfterRec=(expression)($bVerifyRecPass == 1)&&[string equal -nocase "<Type>" "ciscoenable"]
IsEnableExt3=(expression)[string equal -nocase "<extrapass3\Type>" "ciscoenable"]
IsEnableExt2=(expression)[string equal -nocase "<extrapass2\Type>" "ciscoenable"]

#CheckIfUsernameContainsForbiddenCharactersOrWords
ContainsForbiddenCharsOrWords=(expression)$bContainsBlacklistCharsOrWords
NotContainsForbiddenCharsOrWords=(expression)(!$bContainsBlacklistCharsOrWords)

#Base version of TACACS
DoesTacacsAuthParameterEnabled=(expression)[string equal -nocase "<TacacsAuth>" "yes"]
DoesTacacsAuthParameterDisabled=(expression)![string equal -nocase "<TacacsAuth>" "yes"]
DoesTacacsAuthEnabled=(expression)$bTacacsAuth == 1
DoesTacacsAuthDisabled=(expression)$bTacacsAuth == 0

DoesPreviousPasswordHashSet=(expression)$bPreviousPasswordHashSet == 1
DoesPreviousPasswordHashNotSet=(expression)$bPreviousPasswordHashSet == 0
DoesPasswordExist=username .* privilege
DoesCommandWorks=.*
GPHIsNotChangedPasswordHash=(expression)[string equal -nocase "$bPreviousPasswordHash" "$bNewPasswordHash"]
GPHIsChangedPasswordHash=(expression)![string equal -nocase "$bPreviousPasswordHash" "$bNewPasswordHash"]